application: snippets
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /google_activity_matcher/match
  script: google_activity_matcher/match.php

- url: /geocoder/geocoder
  script: geocoder/geocoder.php5


- url: /geocoder/test
  script: geocoder/test.php5

- url: /regression_scheduler
  script: regression_scheduler/index.php

- url: /submitRegression.php
  script: regression_scheduler/submitRegression.php

- url: /deleteRegression.php
  script: regression_scheduler/deleteRegression.php


- url: /assets/css
  static_dir: assets/css

