application: snippets
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /google_activity_matcher/match
  script: google_activity_matcher/match.php

- url: /geocoder/geocoder
  script: geocoder/geocoder.php5


- url: /geocoder/test
  script: geocoder/test.php5

- url: /regression_scheduler
  script: regression_scheduler/index.php5

- url: /submitRegression.php5
  script: regression_scheduler/submitRegression.php5

- url: /deleteRegression.php5
  script: regression_scheduler/deleteRegression.php5

- url: /startDigitalocean.php5
  script: regression_scheduler/startDigitalocean.php5

- url: /stopDigitalocean.php5
  script: regression_scheduler/stopDigitalocean.php5

- url: /snapshotDigitalocean.php5
  script: regression_scheduler/snapshotDigitalocean.php5


- url: /assets/css
  static_dir: assets/css

